// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  group("Production", function() {
    postman[Request]({
      name: "DoSearch2",
      id: "8ea1d8c0-5d33-478e-8ff9-11ec3be9d7bc",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/DoSearch2?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&CountryID=1&PostalCode=08876&Radius=5&PageSize=25",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetUser",
      id: "f51b4bb7-e585-4843-affa-db31dc4602be",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/GetUser?APIKey=e1cdc610-55d8-4eb7-943b-54b123615ba9&ClientID=267&memberKey=joshua123@test.electricvine.com"
    });

    postman[Request]({
      name: "CreateUser",
      id: "e7044849-6819-4414-b587-5c00fcc77257",
      method: "POST",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/CreateUser",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"newUserName": "newuser2@test.electricvine.com",\r\n\t\t"newPassword": "password",\r\n\t\t"newUserRole" : "dealeruser",\r\n\t\t"relatedId" : "3706083"\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "CreateUser copy",
      id: "3c919559-72ac-4a78-b5ba-82a4d48e7dfa",
      method: "POST",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/CreateUser",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"newUserName": "newuserNEW@test.electricvine.com",\r\n\t\t"newPassword": "password",\r\n\t\t"newUserRole" : "dealeruser",\r\n\t\t"relatedId" : "3706083"\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "GetLocationByIP",
      id: "9022d684-b29b-4555-ac4b-a59b3772e8d5",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetLocationByIP?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&IPaddress=199.199.1.238",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetClientSubsFeatures",
      id: "f7520357-e103-4515-94d9-7f03fc29c19e",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetLocationByIP?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&IPaddress=199.199.1.238",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetGeneralClientConfig",
      id: "84038e70-f011-439a-bf51-199399152865",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetGeneralClientConfig?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&InterfaceConfigId=1827",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetAllClientSearchSettings",
      id: "d005a566-dd31-469b-be2c-dd0da5008de6",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetAllClientSearchSettings?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "ValidateClient",
      id: "fdd3050f-ac53-4217-a311-54ca7d8a549c",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestAdmin.svc/ValidateClient?APIKey=70ABCF39-D794-48D8-BBCF-F413B1AEA64C&UserName=musicstaff@musicstaff.com&Password=password"
    });

    postman[Request]({
      name: "Add Lead",
      id: "7040dbb5-ed48-4ff5-babb-23ca47317aa3",
      method: "POST",
      address: "http://ws.bullseyelocations.com/RestLead.svc/AddLead",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "a07c1ab5-3976-413b-8e48-aee7e8d3d967",\r\n\t\t"EmailLead": "false",\r\n\t\t"EmailDealers" : "false",\r\n\t\t"FirstName": "Joshua",\r\n\t\t"LastName": "Rich",\r\n\t\t"CompanyName": "EVI Test",\r\n\t\t"EmailAddress": "jrich@test.electricvine.com",\r\n\t\t"Address1": "3121 US HWY 22",\r\n\t\t"Address2": "Suite 301",\r\n\t\t"City": "Branchburg",\r\n\t\t"StateAbbr": "NJ",\r\n\t\t"PostalCode": "08876",\r\n\t\t"CountryID": "1",\r\n\t\t"PhoneNumber": "123-123-1234",\r\n\t\t"Comments": "This is a test",\r\n\t\t"PriorityID":"3",\r\n\t\t"LeadSourceID":"320",\r\n\t\t"LocationID":"8124139"\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });
  });

  group("Staging", function() {
    postman[Request]({
      name: "Add Lead",
      id: "a0cd2e01-6f8b-4058-adf1-1ae1b8bab4d2",
      method: "POST",
      address: "http://ws.staging.bullseyelocations.com/RestLead.svc/AddLead",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"EmailLead": "false",\r\n\t\t"EmailDealers" : "false",\r\n\t\t"NewLead":\t\r\n\t\t\t{\r\n\t\t\t"CountryID": 1,\r\n\t\t\t"FirstName": "Joshua",\r\n\t\t\t"LastName": "Rich",\r\n\t\t\t"CompanyName": "EVI Test",\r\n\t\t\t"EmailAddress": "jrich@test.electricvine.com",\r\n\t\t\t"Address1": "3121 US HWY 22",\r\n\t\t\t"Address2": "Suite 301",\r\n\t\t\t"City": "Branchburg",\r\n\t\t\t"StateAbbr": "NJ",\r\n\t\t\t"PostalCode": "08876",\r\n\t\t\t"PhoneNumber": "123-123-1234",\r\n\t\t\t"Comments": "This is a test",\r\n\t\t\t"PriorityID": 3,\r\n\t\t\t"LeadSourceID": 320\r\n\t\t\t}\t\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "DoSearch2",
      id: "b90cb1f8-bb74-4505-8fcd-08f061788c7e",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/DoSearch2?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&CountryID=1&PostalCode=08876&Radius=5&PageSize=25",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetUser",
      id: "b62f2b9a-4e11-4361-ae9f-88642a8e3fe7",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/GetUser?APIKey=e1cdc610-55d8-4eb7-943b-54b123615ba9&ClientID=267&memberKey=joshua123@test.electricvine.com"
    });

    postman[Request]({
      name: "CreateUserScott",
      id: "ae0ba746-b5e2-4766-b893-a330d32f5d0e",
      method: "POST",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/CreateUser",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"newUserName": "newuser2@test.electricvine.com",\r\n\t\t"newPassword": "password",\r\n\t\t"newUserRole" : "dealeruser",\r\n\t\t"relatedId" : "3706083"\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "CreateUser",
      id: "867fd4c0-9360-4acc-bbe0-a6ea5d0716d2",
      method: "POST",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/CreateUser",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"newUserName": "newuser2@test.electricvine.com",\r\n\t\t"newPassword": "password",\r\n\t\t"newUserRole" : "dealeruser",\r\n\t\t"relatedId" : "3706083"\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "GetLocationByIP",
      id: "bf5779f5-7c7c-4a5d-869b-79bb4e4f4ced",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetLocationByIP?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&IPaddress=199.199.1.238",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetClientSubsFeatures",
      id: "600f2668-1388-44b3-99e4-b94fffdfd4f6",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetLocationByIP?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&IPaddress=199.199.1.238",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetGeneralClientConfig",
      id: "4d72a37b-4f83-4ace-b6a0-213ea428c68c",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetGeneralClientConfig?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&InterfaceConfigId=1827",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetAllClientSearchSettings",
      id: "d1b75953-33c1-4a5e-ba4d-9ee0f8cb5a5a",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetAllClientSearchSettings?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "ValidateClient",
      id: "21bed748-7633-46eb-b7cd-382467c6c1af",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestAdmin.svc/ValidateClient?APIKey=70ABCF39-D794-48D8-BBCF-F413B1AEA64C&UserName=musicstaff@musicstaff.com&Password=password"
    });
  });

  group("Staging 2", function() {
    postman[Request]({
      name: "DoSearch2",
      id: "b5c1d9e8-c03c-402a-8d15-28dd2cc6c9d4",
      method: "GET",
      address:
        "http://leadmanagerws.staging2.electricvine.com/RestSearch.svc/DoSearch2?APIKey=dd9da999-c6e7-4f06-93e6-39dcd5a5acae&ClientID=5870&CountryID=1&PostalCode=08876&Radius=5&PageSize=25&LanguageID=&LanguageCode=FR",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetUser",
      id: "9953843f-717a-4538-8156-edd48631f9a0",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/GetUser?APIKey=e1cdc610-55d8-4eb7-943b-54b123615ba9&ClientID=267&memberKey=joshua123@test.electricvine.com"
    });

    postman[Request]({
      name: "CreateUser",
      id: "b24723c0-3713-4eea-ae42-cb0fdb04fc0d",
      method: "POST",
      address:
        "http://ws.staging.bullseyelocations.com/RestUser.svc/CreateUser",
      data:
        '{\r\n\t\t"ClientId": "267",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"newUserName": "newuser2@test.electricvine.com",\r\n\t\t"newPassword": "password",\r\n\t\t"newUserRole" : "dealeruser",\r\n\t\t"relatedId" : "3706083"\r\n}\t\t\r\n',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "GetLocationByIP",
      id: "7692ff1d-e01f-486f-8c04-26a96d44a602",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetLocationByIP?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&IPaddress=199.199.1.238",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetClientSubsFeatures",
      id: "1f9f5180-d7bc-4fb5-8f83-794e73bc7c11",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetLocationByIP?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267&IPaddress=199.199.1.238",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetGeneralClientConfig",
      id: "073e7258-523d-4fe5-a7ce-97248f4e936a",
      method: "GET",
      address:
        "http://leadmanagerws.staging2.electricvine.com/RestSearch.svc/GetGeneralClientConfig?APIKey=388a9612-e6b3-42d9-a661-59535243479b&ClientID=5874&InterfaceConfigId=6157&LanguageID=48",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetAllClientSearchSettings",
      id: "ee663aea-b3d7-47af-b0ad-7af53028c333",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestSearch.svc/GetAllClientSearchSettings?APIKey=4630872d-1c75-4a33-ac4c-09e553d53242&ClientID=267",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "ValidateClient",
      id: "a7b6e164-3370-462d-a4a1-24d8b39cee60",
      method: "GET",
      address:
        "http://ws.staging.bullseyelocations.com/RestAdmin.svc/ValidateClient?APIKey=70ABCF39-D794-48D8-BBCF-F413B1AEA64C&UserName=musicstaff@musicstaff.com&Password=password"
    });

    postman[Request]({
      name: "GetClientTerms",
      id: "9986fe21-75a3-4a94-b0e7-a2fac027e438",
      method: "GET",
      address:
        "http://leadmanagerws.staging2.electricvine.com/RestSearch.svc/GetClientTerms?APIKey=dd9da999-c6e7-4f06-93e6-39dcd5a5acae&ClientID=5870&LanguageID=48",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetCategories",
      id: "7c95b551-f542-4918-82fc-60f9e2efdc2a",
      method: "GET",
      address:
        "http://leadmanagerws.staging2.electricvine.com/RestEventSearch.svc/GetCategories?APIKey=dd9da999-c6e7-4f06-93e6-39dcd5a5acae&ClientID=5870&LanguageCode=FR&LanguageID=148",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "GetLocation",
      id: "e6331ac9-c5c4-4ebb-9d71-11ae21f440b9",
      method: "GET",
      address:
        "http://leadmanagerws.staging2.electricvine.com/RestSearch.svc/GetLocation?APIKey=dd9da999-c6e7-4f06-93e6-39dcd5a5acae&ClientID=5870&LanguageID=&LanguageCode=FR&LocationID=4952378&ThirdPartyID=",
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });

    postman[Request]({
      name: "AddLead",
      id: "72c5af62-1737-49a7-b592-f9842a2f82ef",
      method: "POST",
      address:
        "http://leadmanagerws.staging2.electricvine.com/RestLead.svc/AddLead",
      data:
        '{\r\n\t\t"ClientId": "4837",\r\n\t\t"ApiKey": "e1cdc610-55d8-4eb7-943b-54b123615ba9",\r\n\t\t"NewLead": "",\r\n\t\t"EmailLead": "True",\r\n\t\t"EmailDealers" : "True",\r\n}\t',
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        var responseJSON;
        try {
          tests["Body contains headers"] = responseBody.has("headers");
          responseJSON = JSON.parse(responseBody);
          tests["Header contains host"] = "host" in responseJSON.headers;
          tests[
            "Header contains test parameter sent as part of request header"
          ] = "my-sample-header" in responseJSON.headers;
        } catch (e) {}
      }
    });
  });
}
